- charms/kfp-api/src/charm.py
- tests/test_pipelines.py
kfp-api creates an extra Service object called `ml-pipeline` to be compatible with upstream Kubeflow. On Juju versions < 2.9, this Service object used a selector of `juju-app: kfp-api`. However, starting with Juju 2.9, that selector needs to be `app.kubernetes.io/name: kfp-api` instead.
Fixes #6
> Fix kfp-api extra service name

- charms/kfp-profile-controller/files/upstream/sync.py
- charms/kfp-profile-controller/src/charm.py
This change partly addresses https://github.com/canonical/bundle-kubeflow/issues/423
This updates the kfp metacontroller managed by the kfp-profile-controller to add a new PodDefault to all user namespaces (Profiles).  This PodDefault, when selected, lets Notebooks access the pipelines client without explicitly authenticating.
The change here adds the PodDefault, but it does not automatically enable the kfp access.  PodDefaults in a user's namespace are noticed by the notebook controller (charm: jupyter-ui) and shown to a user in the Notebook spawner UI under "Configurations".  To enable this kfp integration, users must enable this new configuration "Allow access to Kubeflow Pipelines".
This PodDefault can also be used by other workloads that might need access, such as a step of a …
> add a PodDefault for pipelines access to all Profiles

- charms/kfp-profile-controller/src/charm.py
- charms/kfp-profile-controller/tests/integration/test_charm.py
Fixes an issue where the metacontroller defined by the kfp-profile-controller does not update the object storage credentials (stored in the `mlpipeline-minio-artifact` secret in each user's namespace), even though the kfp-profile-controller itself is informed of the new creds.  This was caused by using the `OnDelete` update mode in the metacontroller, which will only update the object if it is fully deleted (and not if it has just changed).  This is now set to `InPlace`, which always updates the object if the desired state differs from the current state (similar to if you did a `kubectl apply`).
Closes #56
> fix: ensure minio creds in namespace are updated on change

- charms/kfp-api/tox.ini
- charms/kfp-profile-controller/tox.ini
Unpinned `pytest-operator<0.17.0` due to recent `pytest-operator` update which fixed the teardown issues.
> Unpinned pytest-operator version

- charms/kfp-profile-controller/metadata.yaml
- charms/kfp-profile-controller/src/charm.py
This updates the profile controller to kfp v2.0.0-alpha.3.  No workload needs to be updated as this component has no binary workload
> update config options for kfp-profile-controller per kfp v2.0.0-alpha.3

- charms/kfp-api/tests/integration/test_charm.py
Updates test to explicitly call out relations.  Refactors tests for consistency with others.
> fix: kfp-api observability integration tests

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
- .github/workflows/release.yaml
- charms/kfp-api/tox.ini
- charms/kfp-persistence/tox.ini
- charms/kfp-profile-controller/tox.ini
- charms/kfp-schedwf/tox.ini
- charms/kfp-ui/tox.ini
- charms/kfp-viewer/tox.ini
- charms/kfp-viz/tox.ini
Some of the test dependencies that rely on flake8 are failing with the latest version, therefore we will pin to 4.0.1 for now.
Additionally some things have changed in charmcraft 2.0.0 breaking the previous charming-actions version, therfore we also upgrade it to 2.0.0-rc.
> Pin flake8 to 4.0.1 and upgrade charming-actions

- .github/workflows/integrate.yaml
This is a temporary fix to address [this bug](https://bugs.launchpad.net/juju/+bug/1992833).  In particular, leaving the agent-version unpinned results in the kfp-api observability tests to fail with prometheus-k8s failing in either the stop hook or the metrics-endpoint-relation-changed hook
> fix: pin integration CI to juju agent-version=2.9.34

- bundle.yaml
- tests/integration/data/kfp_against_latest_edge.yaml
- tests/integration/test_bundle.py
This PR fixes two breaks in the bundle integration tests:
* kubeflow-dashboard has been refactored and now needs --trust.  This is added here
* an old mariadb charm was incorrectly being pulled from the charm store, silently causing errors.  This has been updated, and an error check added to catch bundle deploy errors more overtly in future.
This PR is based on #115.  #115 should be merged first.
> fix: bundle integration tests

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
- .github/workflows/release.yaml
- bundle.yaml
- charms/kfp-api/metadata.yaml
- charms/kfp-persistence/metadata.yaml
- charms/kfp-persistence/src/charm.py
- charms/kfp-profile-controller/README.md
- charms/kfp-schedwf/metadata.yaml
- charms/kfp-ui/metadata.yaml
- charms/kfp-viewer/metadata.yaml
- charms/kfp-viz/metadata.yaml
- tests/integration/data/kfp_against_1.6_edge.yaml
- tests/integration/data/kfp_against_latest_edge.yaml
This bumps kfp to the version released with the 1.6.1 Kubeflow release. It also fixes CI to address backwards-incompatible changes that occurred to charmcraft, and pins tests to use 1.6/edge rather than latest/edge.
> feat: bump track 2.0 to kfp released for KF 1.6.1, fix CI

- charms/kfp-api/metadata.yaml
- charms/kfp-persistence/metadata.yaml
- charms/kfp-profile-controller/metadata.yaml
- charms/kfp-profile-controller/tests/integration/test_charm.py
- charms/kfp-ui/metadata.yaml
- charms/kfp-viz/metadata.yaml
- tests/integration/data/kfp_against_latest_edge.yaml
This vendors all remotely defined serialized-data-interface schemas, embedding them in the respective metadata.yaml(s) rather than storing them as a remote link.  This is to enable offline deployment of the charms, as described in [jira](https://warthogs.atlassian.net/browse/KF-727?atlOrigin=eyJpIjoiN2JjZTdlMGYxNDQ3NDdlYzljZDQxNDQ1MTk0OTdkNTEiLCJwIjoiaiJ9).
Also fixed here is the integration CI for kfp-profile-controller.  This CI has been refactored to improve robustness to address flaky failures.
> feat: localize SDI schemas

- charms/kfp-api/requirements-integration.in
- charms/kfp-persistence/requirements-integration.in
- charms/kfp-profile-controller/requirements-integration.in
- charms/kfp-schedwf/requirements-integration.in
- charms/kfp-ui/requirements-integration.in
- charms/kfp-viewer/requirements-integration.in
- charms/kfp-viz/requirements-integration.in
Apparently the juju agent 2.9.34 is not compatible with pythonlib-juju 3.1, causing the following error:
juju.errors.JujuConnectionError: juju server-version 2.9.34 not supported To avoid this, we have to pin to a version below 3.1.
> tests: pin python-libjuju<3.1 to avoid unsupported version errors

- .github/workflows/integrate.yaml
The juju agent 2.9.42 should fix https://bugs.launchpad.net/juju/+bug/1992833.
Expected CI failures:
* `application-kfp-api: 22:03:48 ERROR unit.kfp-api/0.juju-log kfp-viz:18: Encountered the following exception when parsing mysql relation: list index out of range` or similar. This will be fixed in https://github.com/canonical/kfp-operators/pull/176
This, along with changes in #178  and #176 have been tested together [here](https://github.com/canonical/kfp-operators/actions/runs/4509420822). We can merge this PR in the dev branch to later merge it into main.
> ci: bump juju agent 2.9.34 -> 2.9.42

- charms/kfp-api/tests/integration/test_charm.py
Observability charms need more time to be deployed in Github runners.
Merge after #177 
Expected CI failures:
* `application-kfp-api: 22:03:48 ERROR unit.kfp-api/0.juju-log kfp-viz:18: Encountered the following exception when parsing mysql relation: list index out of range` or similar. This will be fixed in #176 
* Timeouts when deploying grafana and/or prometheus. This will be fixed in #177 
This, along with changes in #177 and #176 have been tested together [here](https://github.com/canonical/kfp-operators/actions/runs/4509420822). We can merge this PR in the dev branch to later merge it into main.
> tests: increase timeout for waiting obs charms to be active

- charms/kfp-api/src/charm.py
- charms/kfp-api/tests/unit/test_operator.py
The previous way of retrieving relation data from the `mysql` relation caused issues when there no remote unit joined the relation, or the relation data bag was empty (see more details of this issue in #163). Refactoring the method that retrieves relation data prevents this from happening.
Failing integration tests will be fixed by #177 and #178, please merge only after those two PRs are also merged. 
This, along with changes in #177 and #178  have been tested together [here](https://github.com/canonical/kfp-operators/actions/runs/4509420822). We can merge this PR in the dev branch to later merge it into main.
> refactor: use get_relation and data to get relation data from myql relation

- .github/workflows/publish.yaml
- .github/workflows/release.yaml
Pin to new version to fix the action trying to replace special characters in the CH branch name.
> ci: bump charming-actions 2.2.4->2.2.5

- charms/kfp-api/src/charm.py
- charms/kfp-api/tests/unit/test_operator.py
Sleep for 1 second before attempting to start the KFP API server, in order to avoid issues with Pebble when the corresponding service fails fast. This is a temporary measure until a fix for canonical/pebble#240 is provided.
Refs #220
> pebble: Sleep before starting KFP API server

- charms/kfp-api/src/templates/ml-pipeline-service.yaml.j2
* Hardcode the name of the Service to `ml-pipeline` to match the value set upstream
Currently (following the KFP API sidecar rewrite), we submit the Kubernetes Service corresponding to the API Server ourselves when installing the charm. In doing so, we set its name to `kfp-api`. However, this clashes with the value used by default by the KFP client for in-cluster executions.
* Switch the values of the GRPC and HTTP `targetPorts` to match the ones found in the upstream manifests:
Note that this does not show in our deployments, since the `KubernetesResourcePatcher` immediately patches the service.
* GRPC: 8887
* HTTP: 8888
> feat: Fix KFP API Server K8s Service

- .github/workflows/integrate.yaml
Removes incorrect `-oyaml` option from describe command when saving logs.
> ci: remove `-oyaml` from describe command

- charms/kfp-ui/lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py
- charms/kfp-ui/lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_sidebar.py
- charms/kfp-ui/metadata.yaml
- charms/kfp-ui/src/charm.py
Adds the sidebar relation for kubeflow-dashboard, plus the library to manage it.  This allows this charm to request a link in the kubeflow dashboard's sidebar.
> feat: add kubeflow-dashboard sidebar relation

- charms/kfp-schedwf/charmcraft.yaml
- charms/kfp-viewer/charmcraft.yaml
Installing these missing python packages so the charm gets the latest version of `pip` and `setuptools`.
> build: install setuptools and pip in charms that are missing it

- charms/kfp-api/pyproject.toml
- charms/kfp-api/tests/integration/test_charm.py
- charms/kfp-api/tests/unit/__init__.py
- charms/kfp-api/tox.ini
- charms/kfp-persistence/pyproject.toml
- charms/kfp-persistence/src/charm.py
- charms/kfp-persistence/tests/unit/test_operator.py
- charms/kfp-profile-controller/pyproject.toml
- charms/kfp-profile-controller/src/charm.py
- charms/kfp-profile-controller/tests/integration/profile.yaml
- charms/kfp-profile-controller/tests/integration/test_charm.py
- charms/kfp-profile-controller/tests/unit/test_operator.py
- charms/kfp-schedwf/pyproject.toml
- charms/kfp-schedwf/src/charm.py
- charms/kfp-schedwf/tests/unit/test_operator.py
- charms/kfp-ui/pyproject.toml
- charms/kfp-ui/src/charm.py
- charms/kfp-ui/tests/unit/test_operator.py
- charms/kfp-viewer/pyproject.toml
- charms/kfp-viewer/src/charm.py
- charms/kfp-viewer/tests/unit/test_operator.py
- charms/kfp-viz/pyproject.toml
- charms/kfp-viz/src/charm.py
- charms/kfp-viz/tests/unit/test_operator.py
- pyproject.toml
- tests/integration/helpers/localize_bundle.py
Update copyright 202* -> 2023
1. kfp-api individual integration tests will fail due to #243
2. bundle integration tests will fail due to https://github.com/canonical/bundle-kubeflow/issues/648
Merge after #273
> chore: update copyright year

- .github/workflows/integrate.yaml
- charms/kfp-api/tests/integration/test_charm.py
In this PR:
* tests: fix kfp-api integration tests in multiple places
The kfp-api individual tests were failing due to a number of reasons, mainly caused by how
this charm's dependencies are deployed and the time it takes for those to be up and ready.
This commit ensures those dependencies (mysql, minio, prometheus) are active and idle within
a reasonable time to avoid timeouts and charms misconfigurations.
1. For mysql-k8s, the charm is now deployed from channel 8.0/edge, a version that contains the testing
profile option, which constraints the charm in a recommended way to deploy on GitHub runners.
2. For prometheus-k8s, since this charms requires a significant amount of time to deploy, the wait
for idle timeout is increased to 90*20. This change was introduced by …
> ci, tests: fix testing in GH runners for kfp-api individual integration tests

- tests/integration/test_kfp_functional.py
The workaround was added because juju/python-libjuju#900 was causing issues when waiting for podspec charms to be active and idle when deployed alongside sidecar charms. The issue is now fixed and the workaround can be removed.
> tests: remove wait for sidecar charms deployments to be ready and available

- charms/kfp-api/src/charm.py
- charms/kfp-api/src/templates/ml-pipeline-service.yaml.j2
* fix: add ml-pipeline-service.yaml.j2 in K8S_RESOURCE_FILES
The ml-pipeline Service was omitted when applying k8s resources.
IMPORTANT:
* This is a backport from `main` -> `track/2.0`
* The CI is failing due to canonical/bundle-kubeflow#648, #243, and #250, but #290, #292, and #293 should fix it
> fix: add ml-pipeline-service.yaml.j2 in K8S_RESOURCE_FILES (#255)

- .github/workflows/integrate.yaml
- charms/kfp-api/requirements-integration.txt
- charms/kfp-api/requirements-unit.txt
- charms/kfp-api/requirements.txt
- charms/kfp-api/src/charm.py
- charms/kfp-api/src/templates/ml-pipeline-service.yaml.j2
- charms/kfp-api/tests/integration/test_charm.py
- charms/kfp-persistence/requirements-integration.txt
- charms/kfp-persistence/requirements-unit.txt
- charms/kfp-persistence/requirements.in
- charms/kfp-persistence/requirements.txt
- charms/kfp-profile-controller/requirements-integration.txt
- charms/kfp-profile-controller/requirements-unit.txt
- charms/kfp-profile-controller/requirements.in
- charms/kfp-profile-controller/requirements.txt
- charms/kfp-schedwf/requirements-integration.txt
- charms/kfp-schedwf/requirements-unit.txt
- charms/kfp-schedwf/requirements.txt
- charms/kfp-ui/requirements-integration.txt
- charms/kfp-ui/requirements-unit.txt
- charms/kfp-ui/requirements.in
- charms/kfp-ui/requirements.txt
- charms/kfp-viewer/requirements-integration.txt
- charms/kfp-viewer/requirements-unit.txt
- charms/kfp-viewer/requirements.txt
- charms/kfp-viz/requirements-integration.txt
- charms/kfp-viz/requirements-unit.txt
- charms/kfp-viz/requirements.txt
Merge a collection of chores and fixes from dnplas-dev-fix-ci into main. All commits in this PR have been already reviewed, in their respective PRs.
Changes:
* fix: add ml-pipeline-service.yaml.j2 in K8S_RESOURCE_FILES (https://github.com/canonical/kfp-operators/pull/255) (https://github.com/canonical/kfp-operators/pull/279)
* ci, tests: fix testing in GH runners for kfp-api individual integration tests (https://github.com/canonical/kfp-operators/pull/273)
* build: bump juju 2.9.44.0, sdi->0.7.0, pyyaml->6.0.1 (https://github.com/canonical/kfp-operators/pull/290)
* ci, tests: fix testing in GH runners for kfp-api individual integration tests (https://github.com/canonical/kfp-operators/pull/273) (https://github.com/canonical/kfp-operators/pull/292)
* ci, build: use action to free space …
> Merge `KF-4149-dev-branch` into `main`

- tools/get-images.sh
Used by CVE scanning workflows and can be used to collect images URL for airgapped setup. Script is specific for track/2.0 branch to capture all images for that branch. Branch is handled in kubeflow-ci and bundle automation using bundle file.
- Re-designed get images script to retrieve all images for current branch. Branch management is done outside of this script.
> feat: get images script for track/2.0

- .github/workflows/integrate.yaml
`Upload debug artifacts` was left behind when 7db9c0c was merged.
> ci: remove unsed step from integrate workflow

- charms/kfp-api/src/charm.py
- charms/kfp-api/tests/integration/test_charm.py
- charms/kfp-api/tests/unit/test_operator.py
In the kfp-api charm, `*-relation-broken` events trigger the same workflow as every other event, forcing the charm to recalculate its configuration. In order to do that, it attempts to retrieve info from its required relations. When executing in response to a relation-broken event for a removed `relational-db` relation, however, the library call to fetch the data raises an error. We need to catch this error and properly propagate it so that the charm lands in the desired state (i.e. Blocked, waiting for the required relation to be added).
Closes #222
> fix: Handle relation-broken events

- charms/kfp-profile-controller/tests/integration/test_charm.py
The `kfp-profile-controller` integration tests are sometimes failing, due to `wait_for_idle` being set to wait for the `kfp-profile-controller` charm only. This means other charms might not be ready when the `test_build_and_deploy` is done, making this test incorrect, and causing other tests to fail.
Fixed by removing the `apps=[CHARM_NAME]` in `wait_fot_idle`, so it waits for all apps.
> fix: profile-controller integration tests wait_for_idle

- charms/kfp-viz/README.md
- charms/kfp-viz/lib/charms/observability_libs/v1/kubernetes_service_patch.py
- charms/kfp-viz/metadata.yaml
- charms/kfp-viz/requirements-unit.in
- charms/kfp-viz/requirements-unit.txt
- charms/kfp-viz/requirements.in
- charms/kfp-viz/requirements.txt
- charms/kfp-viz/src/charm.py
- charms/kfp-viz/src/components/pebble_components.py
- charms/kfp-viz/tests/unit/test_operator.py
- tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
- tests/integration/bundles/kfp_latest_edge.yaml.j2
based on #305 due to unverified commits
Rewrite the `kfp-viz` charm, migrating it from podspec to sidecar using the reusable base charm in charmed-kubeflow-chisme. More details on the base charm [in this README.md](https://github.com/canonical/charmed-kubeflow-chisme/tree/main/src/charmed_kubeflow_chisme/components#readme)
- rewrites all charm logic in terms of Components
- implements the Pebble container
- implements the relation handler
- refactors the unit tests to use the base charm tooling
- modifies requirements.in and requirements-unit.in and updates the requirements-*.txt's
**NOTE:** Due to deployment parameter in PodSpec version, kfp-persistence cannot be upgraded using Juju refresh:
juju.errors.JujuAPIError: Juju on containers does not support updating deployment info for …
> feat: kfp-viz sidecar rewrite with base charm

- charms/kfp-api/requirements-integration.txt
- charms/kfp-persistence/requirements-integration.txt
- charms/kfp-profile-controller/requirements-integration.txt
- charms/kfp-schedwf/requirements-integration.txt
- charms/kfp-ui/requirements-integration.txt
- charms/kfp-viewer/requirements-integration.txt
- charms/kfp-viz/requirements-integration.txt
- requirements-integration.txt
Upgrade python-libjuju to 2.9.44.1 which fixes issues in our integration tests that deploy `mysql-k8s` from `8.0/edge`.
Closes https://github.com/canonical/kfp-operators/issues/316
> fix: Bump libjuju to 2.9.44.1

- charms/kfp-profile-controller/lib/charms/observability_libs/v1/kubernetes_service_patch.py
- charms/kfp-profile-controller/src/charm.py
- charms/kfp-profile-controller/tests/integration/test_charm.py
- charms/kfp-profile-controller/tests/unit/test_operator.py
* Patch the port specified in the K8s service created by Juju to point to the one the controller pod responsible for running the `sync.py` script listens to
* Add an integration test to verify that the sync webhook has applied all desired resources. In order for the test to work (and the metacontroller to be deployed successfully) we also deploy the admission-webhook which is responsible for applying the PodDefault CRD. Until https://github.com/canonical/metacontroller-operator/issues/86 is closed, we need to ensure that this completes successfully before the metacontroller is deployed.
Closes https://github.com/canonical/kfp-operators/issues/317
Refs https://github.com/canonical/kfp-operators/issues/314
> fix: Patch KFP Profile Controller service port

- .github/workflows/integrate.yaml
- charms/kfp-api/requirements-integration.in
- charms/kfp-api/requirements-integration.txt
- charms/kfp-persistence/requirements-integration.in
- charms/kfp-persistence/requirements-integration.txt
- charms/kfp-profile-controller/requirements-integration.in
- charms/kfp-profile-controller/requirements-integration.txt
- charms/kfp-schedwf/requirements-integration.in
- charms/kfp-schedwf/requirements-integration.txt
- charms/kfp-ui/requirements-integration.in
- charms/kfp-ui/requirements-integration.txt
- charms/kfp-viewer/requirements-integration.in
- charms/kfp-viewer/requirements-integration.txt
- charms/kfp-viz/requirements-integration.in
- charms/kfp-viz/requirements-integration.txt
- requirements-integration.in
- requirements-integration.txt
ci: update juju to 3.1 and microk8s to 1.25
> ci: update juju to 3.1 and microk8s to 1.25

- charms/kfp-persistence/src/charm.py
- charms/kfp-persistence/src/components/pebble_components.py
Currently, we provide the --namespace option when starting the persistence agent, setting its value to match that of the model where the charm is deployed. However, this won't work for multi-user Kubeflow installations, where the namespace value should be empty as per the corresponding upstream [manifests](https://github.com/kubeflow/manifests/blob/92542398b2efbbfd9498e40a7cef6e94c68430bf/apps/pipeline/upstream/base/installs/multi-user/persistence-agent/deployment-patch.yaml#L14-L15).
Closes https://github.com/canonical/kfp-operators/issues/323
> fix: Unset namespace in persistence agent config

- charms/kfp-api/src/templates/auth_manifests.yaml.j2
kfp-api was rewritten to a sidecar charms that can create its own aggregation ClusterRoles
This moves the aggregation ClusterRoles from https://github.com/canonical/kubeflow-roles-operator/tree/main/src/manifests to its own charm.
PR in `kubeflow-roles-operator` to remove those same roles from the kubeflow-roles charm https://github.com/canonical/kubeflow-roles-operator/pull/71
> feat: move aggregation roles from kubeflow-roles

- charms/kfp-persistence/requirements-unit.txt
- charms/kfp-persistence/requirements.in
- charms/kfp-persistence/requirements.txt
- charms/kfp-persistence/src/charm.py
- charms/kfp-persistence/src/templates/auth_manifests.yaml.j2
- charms/kfp-persistence/tests/unit/test_operator.py
Apply auth manifests (KF 1.8) for the KFP Persistence Agent, including the ClusterRole, ClusterRoleBinding, and ServiceAccount that allow the workload to get, list, and watch workflows/scheduledworkflows, as well as get namespaces.
> fix: Add Persistence Agent ClusterRole and Binding

- tools/get-images.sh
Modify `get-images.sh` script in order to include cache-image from config.yaml file.
Refs #335
> scripts(get-images): Include cache-image config

- tools/get-images.sh
This PR backports #336 to `main` branch.
> port(script get-images): Include cache-image config (#336)

- charms/kfp-api/src/charm.py
- charms/kfp-api/tests/integration/test_charm.py
- charms/kfp-api/tests/unit/test_operator.py
* api: Handle relation-broken events
In the kpf-api charm, '*-relation-broken' events trigger the same workflow as every other event, forcing the charm to recalculate its configuration. In order to do that, it attempts to retrieve info from its required relations. When executing in response to a relation-broken event for a removed relational-db relation, however, the library call to fetch the data raises an error. We need to catch this error and properly propagate it so that the charm lands in the desired state (i.e. Blocked, waiting for the required relation to be added).
Closes #222
> backport(fix): Handle relation-broken events (#272)

- charms/kfp-schedwf/src/charm.py
- charms/kfp-schedwf/src/components/pebble_component.py
This commit explicitly sets the `command` field in the pebble Layer instead of relying on the rock to configure the service.
> fix: explicitly set the command for schedwf pebble Layer

- charms/kfp-profile-controller/files/upstream/sync.py
- charms/kfp-profile-controller/src/charm.py
- charms/kfp-profile-controller/src/templates/crd_manifests.yaml.j2
- charms/kfp-profile-controller/tests/integration/test_charm.py
Signed commit from here (with discussion) https://github.com/canonical/kfp-operators/pull/342
> Decorator controller rewrite

- charms/kfp-persistence/src/templates/auth_manifests.yaml.j2
The previous CRB was pointing to a SA that is not used by the api server for authentication. The rename was introduced by a244ffe.
> fix: add correct SA name to CRB

- charms/kfp-profile-controller/files/upstream/sync.py
closes https://github.com/canonical/notebook-operators/issues/311 and https://github.com/canonical/kfp-operators/issues/355
1. deploy charmed kubeflow latest/edge
2. refresh the `kfp-profile-controller` charm to the one from this PR
```
juju refresh kfp-profile-controller --channel=latest/edge/pr-356 
```
3. log in to the dashboard and create a namespace
4. check `AuthorizationPolicy` objects in the user's namespace, expect 2 objects:
```
kubectl get authorizationpolicies.security.istio.io -n admin
NAME                            AGE
ns-owner-access-istio-charmed   15s
ns-owner-access-istio           12s
```
5. create a notebook and verify there are no 403 logs from the `jupyter-controller` container
6. create a data passing pipeline and verify that you can download artifacts from …
> fix: apply authorization policy to fix istio traffic issues

- charms/kfp-profile-controller/src/charm.py
fix: use full svc name and namespace for METADATA_GRPC_SERVICE_HOST env var
The METADATA_GRPC_SERVICE_HOST env var has to include the name and namespace of the metadata grpc server, otherwise pipeline runs end in errors when trying to write in the metadata SQLite DB.
This commit reverts [this](https://github.com/canonical/kfp-operators/pull/331/files#diff-7bc4c9be60a555e7b6b00f5fcb1d401ef662bd2853cf38f3b7d9a6d03ce54aa2R52) change introduced in a previous PR.
> fix: include namespace in metadata-grpc-service host name 

- charms/kfp-profile-controller/src/templates/crd_manifests.yaml.j2
removes from `crd_manifests.yaml.j2` the istio resources not used by `kfp-profile-controller`. the resources removed are:
* destinationrules
* authorizationpolicies
this introduced a bug where metacontroller has a dependency on istio, whereas we are disabling istio in the sync.py
closes #373 , more details in the issue.
> fix: remove istio objects from manifests

- charms/kfp-profile-controller/files/upstream/sync.py
kfp-profile-controller implements a sync.py file from upstream which we lightly modify.  This commit reformats that sync.py to be as similar as possible to upstream's sync.py for easier comparison and maintenance.  #331 previously reformatted sync.py to meet our style guide, but that made it harder to track and changes upstream and import them into our version
This should have no functional change on the charm, it only changes things to make maintenance easier.
> reformat kfp-profile-controller's sync.py to match upstream

- charms/kfp-api/metadata.yaml
- charms/kfp-metadata-writer/metadata.yaml
- charms/kfp-persistence/metadata.yaml
- charms/kfp-profile-controller/src/charm.py
- charms/kfp-schedwf/metadata.yaml
- charms/kfp-ui/metadata.yaml
- charms/kfp-viewer/metadata.yaml
- charms/kfp-viz/metadata.yaml
matches images cited in https://github.com/kubeflow/manifests/releases/tag/v1.8.0
> bump image versions to 2.0.2 to match kf 1.8 release

- charms/kfp-api/src/charm.py
- charms/kfp-api/tests/unit/test_operator.py
This PR:
* removes deprecated `DBCONFIG_USER`, etc, environment variables (they have been replaced by variables of name `DBCONFIG_[driver]CONFIG_*`)
* adds `OBJECTSTORECONFIG_HOST`, `_PORT`, and `_REGION`, which previously were required.  Although currently they seem to be ignored due to https://github.com/kubeflow/pipelines/issues/9689 - but in theory they'll matter again?  Not sure exactly the scope of that issue.
afaict, these are both helpful changes.  The first doesn't actually affect anything, but removes unnecessary configs.  The second *should* affect things, if not for https://github.com/kubeflow/pipelines/issues/9689
May close #367
> update kfp-api's apiserver configuration

- charms/kfp-api/tests/integration/test_charm.py
The mysql-k8s charm during deployment sometimes lands temporarily in an error state.  This error state resolves over time and the charm continues on to work as expected, but causes our integration tests to fail (like [this example](https://github.com/canonical/kfp-operators/actions/runs/6907962624/job/18796234535?pr=385#step:5:232)) because we do `wait_for_idle(['mysql-k8s'], ...raise_on_error=True)`.  ~~This fix sets `raise_on_error=False` to avoid this.~~
~~This does not change the passing condition of the test - the test will only pass if mysql-k8s goes to Active/Idle.  The only change is that mysql-k8s going to Error state does not result in a fast failure - the test will continue until the timeout before failing.~~
Edit on 2023-11-20: rather than set `raise_on_error=True`, the …
> fix: reduce flakiness of kfp-api integration tests

- charms/kfp-api/src/charm.py
Refactors kfp-api charm's `on_remove()` event handler to use KubernetesResourceHandler.delete() rather than its own removal procedure.  This was done to:
* standardise on a removal procedure with other charms
* remove the need for the `on_remove()` handler to have a KRH object with full `context`.  In future we will add another Kubernetes object here that requires relation data to render, and this relation data may not be available during the removal event
> refactor kfp-api's on_remove to use KRH built-in delete

- .github/workflows/integrate.yaml
- charms/kfp-api/src/charm.py
- charms/kfp-api/src/templates/minio-service.yaml.j2
- charms/kfp-api/tests/integration/test_charm.py
- charms/kfp-api/tests/unit/test_operator.py
This adds to kfp-api a service called `minio-service` which points to the related object-storage's s3 service.  This has been added to address a bug in upstream kfp, as explained [here](https://github.com/canonical/minio-operator/pull/151).  This service was originally added to the minio charm in [minio pr 151](https://github.com/canonical/minio-operator/pull/151), but has been refactored so it is added here instead as described in [minio issue 153](https://github.com/canonical/minio-operator/issues/153).
* All lint and unit tests should pass.  The kfp-api integration tests should pass, but the bundle tests may fail (are being fixed in a separate parallel PR)
* to manually test:
* deploy kfp-api and required dependencies (an easy way to do this is to run `tox -e integration -- --model …
> add service `minio-service` to kfp api to patch upstream kfp bug

- charms/kfp-profile-controller/src/templates/crd_manifests.yaml.j2
closes #374 
adds comment about being different from upstream manifests
> fix: revert `updateStrategy` of secrets to `InPlace`

- charms/kfp-api/tests/integration/test_charm.py
- tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
- tests/integration/bundles/kfp_latest_edge.yaml.j2
Deploy `mysql-k8s` charm from `8.0/edge` channel in all of our integration tests to address #377. This issue appeared in all our integration tests that deployed the charm. Fix was published in `revision 119` as mentioned in https://github.com/canonical/mysql-k8s-operator/issues/337#issuecomment-1896598221. I also included a comment about moving back to `stable` once the fix is published there too.
Closes #377
> fix(ci): Use mysql-k8s from `8.0/edge`

- charms/kfp-api/tests/integration/test_charm.py
- tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
- tests/integration/bundles/kfp_latest_edge.yaml.j2
Cherry-pick commit from #400.
Deploy `mysql-k8s` charm from `8.0/edge` channel in all of our integration tests.
Refs #377, #401
> cherry-pick(fix ci): Use mysql-k8s from `8.0/edge` from #400

- charms/kfp-profile-controller/src/templates/crd_manifests.yaml.j2
Revert & add a comment about being different from upstream manifests.
Refs #374
> cherry-pick(fix): revert updateStrategy of secrets to InPlace from #395

- .github/workflows/integrate.yaml
backports 5767624da960432766ae748c4c53aa383d07a533 to `track/2.0`
addresses canonical/bundle-kubeflow#813
> ci: Decrease root-reserve-mb to fit the new runner storage (#406)

- tests/integration/data/kfp_against_latest_edge.yaml
Resolves https://github.com/canonical/kfp-operators/issues/420
Pin versions of charms in bundle tests.
NOTE: failing integration tests for kfp-api and kfp-profile-controller are addressed in separate PRs
> Fix bundle integration tests for `track/2.0-alpha.7`

- charms/kfp-profile-controller/tests/integration/test_charm.py
Fixes: https://github.com/canonical/kfp-operators/issues/422
- Fix disk space for github runners 
- Pin versions of charms in integration tests 
- Add `raise on failure false` flag while waiting for deployment
NOTE: failing integration tests for kfp-api and bundle are addressed in separate PRs
> Fix integration tests for kfp-profile-controller for `track/2.0-alpha.7`

- .github/workflows/integrate.yaml
#426 documents that the bundle_v2 integration tests fail due to lack of space on the runner.  This appears to be in part because the action we've used for freeing space in our GH runners (`easimon/maximize-build-space`) no longer frees as much space as it used to.  It used to leave us with >40GB free, but now its around 29GB free.  
Testing with an alternate action for freeing space (`jlumbroso/free-disk-space`) yielded ~45GB free without any adverse side effects noticed, so this PR changes to using that new action.  
Closes #426
> fix bundle_v2 integration tests failures due to running out of space

- .github/workflows/integrate.yaml
> backport fix bundle_v2 integration tests failures due to running out of space on `track/2.0`

- charms/kfp-profile-controller/config.yaml
- charms/kfp-profile-controller/src/charm.py
- charms/kfp-profile-controller/src/default-custom-images.json
- charms/kfp-profile-controller/tests/integration/test_charm.py
This PR fixes https://github.com/canonical/bundle-kubeflow/issues/851 for 1.7.1 kubeflow
New functionality:
- User can override images for `ui-artifact` and `visualizationserver` pods through custom-images config setting.
- Added integration tests which checks that the config change succeeds and that the new profile will have deployments with different images. 
Changes in integration tests 
- had to pin all latest/edge charms 
- now I am also deploying admission webhook so I can check that the resources are really created
CI passes except bundle tests which was previously observed in https://github.com/canonical/kfp-operators/issues/399
> Support functionality to override default images for kfp-profile-controller

- .github/workflows/integrate.yaml
The charmcraft issues that forced us to use destructive mode are now fixed.
See https://github.com/canonical/charmcraft/issues/1138 and https://github.com/canonical/charmcraft/issues/1132
Merge before #436
> ci: remove destructive mode from integration tests

- .github/workflows/integrate.yaml
- charms/kfp-api/charmcraft.yaml
- charms/kfp-metadata-writer/charmcraft.yaml
- charms/kfp-metadata-writer/lib/charms/mlops_libs/v0/k8s_service_info.py
- charms/kfp-metadata-writer/metadata.yaml
- charms/kfp-metadata-writer/requirements-unit.in
- charms/kfp-metadata-writer/requirements-unit.txt
- charms/kfp-metadata-writer/requirements.in
- charms/kfp-metadata-writer/requirements.txt
- charms/kfp-metadata-writer/src/charm.py
- charms/kfp-metadata-writer/src/components/k8s_service_info_requirer_component.py
- charms/kfp-metadata-writer/tests/unit/test_operator.py
- charms/kfp-persistence/charmcraft.yaml
- charms/kfp-profile-controller/charmcraft.yaml
- charms/kfp-schedwf/charmcraft.yaml
- charms/kfp-ui/charmcraft.yaml
- charms/kfp-viewer/charmcraft.yaml
- charms/kfp-viz/charmcraft.yaml
- tests/integration/bundles/kfp_latest_edge.yaml.j2
This PR merges the following changes in `main` as they were introduced in a development branch.
* #441 
* #443 
* #436 
All of them have been tested, reviewed and approved. The CI of this PR must be green before merging into `main`.
> merge `dnplas-dev-branch-fix-ci` in `main`

- .github/workflows/integrate.yaml
- charms/kfp-api/tests/integration/test_charm.py
- charms/kfp-persistence/tests/integration/test_charm.py
- charms/kfp-profile-controller/tests/integration/test_charm.py
- tests/README.md
- tests/integration/bundles/kfp_1.8_stable_install.yaml.j2
This commit pins all charms that get deployed from Charmhub to a compatible version to the CKF 1.8 release.
Part of https://github.com/canonical/bundle-kubeflow/issues/864
> fix: Pin integration test dependencies in track

- charms/kfp-api/tests/integration/test_charm.py
- charms/kfp-persistence/tests/integration/test_charm.py
- charms/kfp-profile-controller/tests/integration/test_charm.py
- tests/README.md
- tests/integration/bundles/kfp_1.8_stable_install.yaml.j2
This commit pins all charms that get deployed from Charmhub to a latest/edge or suggested versions.
Part of canonical/bundle-kubeflow#864
> fix: Pin integration test dependencies in main

- charms/kfp-api/metadata.yaml
- charms/kfp-metadata-writer/metadata.yaml
- charms/kfp-persistence/metadata.yaml
- charms/kfp-schedwf/metadata.yaml
- charms/kfp-ui/metadata.yaml
- charms/kfp-viewer/metadata.yaml
- charms/kfp-viz/metadata.yaml
* Bump ROCKs to 2.0.5.
* Use upstream image for kfp-ui (frontend) due to canonical/pipelines-rocks#80.
Closes #450
> chore: bump images to KFP 2.0.5

- charms/kfp-api/config.yaml
- charms/kfp-api/src/charm.py
- charms/kfp-api/tests/unit/test_operator.py
- tools/get-images.sh
Enable charm configuration of launcher and driver images used during pipeline steps. Those can be configured thourgh values `launcher-image` and `driver-image`. When unset, KFP uses the default images defined in upstream code. This is based on upstream implementation introduced in kubeflow/pipelines#10269.
Closes #452
This was tested with upstream image `gcr.io/ml-pipeline/api-server:2.0.5`. The rest of kfp used the ROCKs.
It can be tested that pipeline steps are using the proper images by configuring the charm and then running a pipeline. 
```bash
juju config kfp-api launcher-image="fake-image"
juju config kfp-api driver-image="fake-image"
```
You should see pods created by the pipeline run that spin up containers using the images provided in the config options.
Note that:
* Each …
> feat(api-server): Enable charm configuration of launcher and driver images

- charms/kfp-api/config.yaml
- charms/kfp-api/src/charm.py
- charms/kfp-api/tests/unit/test_operator.py
- tools/get-images.sh
Enable charm configuration of launcher and driver images used during pipeline steps. Those can be configured through config options `launcher-image` and `driver-image`. When unset, KFP uses the default values defined. This is based on upstream implementation introduced in kubeflow/pipelines#10269.
Closes #453
> backport(feat): Enable configuration in kfp-api of launcher and driver images from #455

- charms/kfp-api/config.yaml
- charms/kfp-api/metadata.yaml
- charms/kfp-api/src/charm.py
- charms/kfp-api/src/templates/auth_manifests.yaml.j2
- charms/kfp-api/tests/unit/test_operator.py
```diff
```
This PR also introduces `argo-aggregate-to-edit` and `argo-aggregate-to-view` ClusterRoles.
Closes #459
> chore: Update kfp-api manifests to 2.2.0

- charms/kfp-viz/metadata.yaml
> chore: Update kfp-viz manifests to 2.2.0

- charms/kfp-viewer/metadata.yaml
> chore: Update kfp-viewer manifests to 2.2.0

- charms/kfp-ui/metadata.yaml
> chore: Update kfp-ui manifests to 2.2.0

- charms/kfp-schedwf/config.yaml
- charms/kfp-schedwf/metadata.yaml
- charms/kfp-schedwf/src/charm.py
- charms/kfp-schedwf/src/components/pebble_component.py
- charms/kfp-schedwf/tests/unit/test_operator.py
> chore: Update kfp-schedwf manifests to 2.2.0

- charms/kfp-persistence/config.yaml
- charms/kfp-persistence/metadata.yaml
- charms/kfp-persistence/src/charm.py
- charms/kfp-persistence/src/templates/auth_manifests.yaml.j2
- charms/kfp-persistence/tests/unit/test_operator.py
This is based on the following commands in https://github.com/kubeflow/manifests/ repo:
```diff
```
Closes #461
> chore: Update kfp-persistence manifests to 2.2.0

- charms/kfp-metadata-writer/metadata.yaml
> chore: Update kfp-metadata-writer manifests to 2.2.0

- charms/kfp-profile-controller/config.yaml
- charms/kfp-profile-controller/src/charm.py
- charms/kfp-profile-controller/src/components/pebble_components.py
- charms/kfp-profile-controller/src/default-custom-images.json
- charms/kfp-profile-controller/tests/integration/test_charm.py
- charms/kfp-profile-controller/tests/unit/test_operator.py
cherry-picks into `track/2.0`:
Support functionality to override default images for kfp-profile-controller (#416)
Fixing as part of the effort to test CKF 1.8 in airgapped, see https://github.com/canonical/bundle-kubeflow/issues/889.
> cherry-pick: Support functionality to override default images for kfp-profile-controller

- charms/kfp-profile-controller/metadata.yaml
- charms/kfp-profile-controller/src/components/pebble_components.py
The KFP Profile Controller is using Python 3.7 which has 7 Critical CVEs. Updating the image to a Canonical maintained ROCK to reduce the number of CVEs. 
**EDIT**: We should update once rockcraft team releases a `stable` version of the image as mentioned [here](https://hub.docker.com/r/ubuntu/python). This should happen in 2-3 weeks.
Running the following command shows that the new image has 0 criticals.
```
docker run -v \ 
/var/run/docker.sock:/var/run/docker.sock \
-v `pwd`:`pwd` \
-w `pwd` \
--rm \
--name=scanner \
aquasec/trivy image --timeout 30m \
-f json -o trivy-report.json --ignore-unfixed \
ubuntu/python:3.8-20.04_edge
```
I updated kfp-profile-controller to the charm from this PR
```
juju refresh kfp-profile-controller --channel latest/edge/pr-477 --resource …
```
> Update KFP Controller Python image to Ubuntu/python rock

- .github/workflows/integrate.yaml
This commit ensures the controller is bootstrapped with version 3.5.0 instead of the default as we have found issues with it.
This is a workaround for canonical/bundle-kubeflow#921.
Fixes #498
> ci: bootstrap juju controller with agent version 3.5.0

- charms/kfp-profile-controller/config.yaml
closes #484 
The default of `custom_images` config in `kfp-profile-controller` charm says `frontend_image` whereas the actual key you should set is just `frontend` as defined in the `.json`
It is currently misleading to users and will cause them to set the config incorrectly, which will then not take effect as expected.
This PR sets the config default to the correct `frontend` value.
> fix: set correct default for custom_images in kfp-profile-controller

- charms/kfp-profile-controller/src/charm.py
- charms/kfp-profile-controller/tests/unit/test_operator.py
closes #485
Fixes the error handling for setting the `custom_images` config in `kfp-profile-controller` charm
* refactors error handling when the `custom_images` config input has incorrect image name
* refactors error handling when the `custom_images` config input is an invalid yaml
* adds unit test for the 2 cases in the above points
> fix: handle incorrect custom images config

- .github/workflows/integrate.yaml
This commit ensures the controller is bootstrapped with version 3.5.0 instead of the default as we have found issues with it.
This is a workaround for canonical/bundle-kubeflow#921.
Fixes #498
> ci: bootstrap juju controller with agent version 3.5.0 (#499)

- charms/kfp-profile-controller/metadata.yaml
- charms/kfp-profile-controller/src/components/pebble_components.py
Update the image to a Canonical maintained ROCK in order to fix #487 and
reduce the number of CVEs.
```bash
juju deploy metacontroller-operator --channel 3.0/stable --trust
juju deploy minio --channel ckf-1.8/stable
juju deploy kfp-profile-controller --channel 2.0/stable --trust --base ubuntu@20.04
juju relate kfp-profile-controller minio
juju status --watch 1s
juju refresh kfp-profile-controller --channel 2.0/edge/pr-501
kubectl -n <namespace> logs kfp-profile-controller-0 -c kfp-profile-controller | grep -i executable
```
Closes #487
> fix: Update KFP Controller Python image to Ubuntu/python rock

- .github/workflows/integrate.yaml
- charms/kfp-viz/lib/charms/loki_k8s/v1/loki_push_api.py
- charms/kfp-viz/metadata.yaml
- charms/kfp-viz/requirements-integration.in
- charms/kfp-viz/requirements-integration.txt
- charms/kfp-viz/requirements-unit.txt
- charms/kfp-viz/requirements.in
- charms/kfp-viz/requirements.txt
- charms/kfp-viz/src/charm.py
- charms/kfp-viz/tests/integration/test_charm.py
- charms/kfp-viz/tests/unit/test_operator.py
Added logging relation and cos integration tests from chisme.
fixes: #491
How I tested it:
from terminal
```bash
$ tox -e integration -- --model kubeflow --keep-models
$ juju consume u1-k8s:cos.loki-logging  # I have pre-deployed cos model
$ juju integrate loki-logging grafana-agent-k8s
$ kubectl get service/kfp-viz -n kubeflow      
NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kfp-viz   ClusterIP   10.152.183.73   <none>        8888/TCP   4m43s
$ curl http://10.152.183.73:8888    
alive
$ curl http://10.152.183.73:8888/test    
<html><title>404: Not Found</title><body>404: Not Found</body></html
```
I visit `http://<ip>/cos-grafana/explore` to explore the logs and see:
> Add logging relation kfp-viz

- charms/kfp-profile-controller/lib/charms/loki_k8s/v1/loki_push_api.py
- charms/kfp-profile-controller/metadata.yaml
- charms/kfp-profile-controller/requirements-integration.in
- charms/kfp-profile-controller/requirements-integration.txt
- charms/kfp-profile-controller/requirements-unit.txt
- charms/kfp-profile-controller/requirements.in
- charms/kfp-profile-controller/requirements.txt
- charms/kfp-profile-controller/src/charm.py
- charms/kfp-profile-controller/tests/integration/test_charm.py
- charms/kfp-profile-controller/tests/unit/test_operator.py
Added logging relation and cos integration tests from chisme.
fixes: #495
How I tested it:
from terminal
```bash
$ tox -e integration -- --model kubeflow --keep-models
$ juju consume u1-k8s:cos.loki-logging  # I have pre-deployed cos model
$ juju integrate loki-logging grafana-agent-k8s
$ juju config kfp-profile-controller custom_images='{"visualization_server": "tanzeyy/visualization_server:v1.0", "frontend": ""}'
```
I visit `http://<ip>/cos-grafana/explore` to explore the logs and see:
> Add logging relation kfp-profile-controller

- tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
- tests/integration/bundles/kfp_1.8_stable_install.yaml.j2
- tests/integration/bundles/kfp_latest_edge.yaml.j2
Since the issue [1] was merged and those changes are already in 8.0/stable, we can use that channel again.
This was observed in [CI run](https://github.com/canonical/kfp-operators/actions/runs/9480339340/job/26127423652?pr=496#step:5:289), and it's related with recent [changes](https://github.com/canonical/mysql-k8s-operator/commit/7273a25e494bfa448980eb5b41c9d75e041ef569) in mysql-k8s charm.
fixes: #401
---
[1]: https://github.com/canonical/mysql-k8s-operator/issues/337
> Reverting to use 8.0/stable for mysql-k8s

- .github/workflows/integrate.yaml
Part of canonical/bundle-kubeflow#944
> ci: use juju 3.4/stable instead of 3.5/stable in track 2.0

- charms/kfp-schedwf/src/charm.py
- charms/kfp-schedwf/src/components/pebble_component.py
Cherry-pick that closes #517 
This PR updates the pebble_components.py file in the kfp-schedwf charm to use a different namespace, similar to the one in [upstream](https://github.com/kubeflow/pipelines/blob/2.0.5/backend/Dockerfile.scheduledworkflow#L49). Also removes the `namespace` field in the relevant Pebble class.
> Cherry pick: Fix recurring runs

- charms/kfp-api/metadata.yaml
- charms/kfp-api/src/charm.py
- charms/kfp-api/tests/unit/test_operator.py
- charms/kfp-metadata-writer/metadata.yaml
- charms/kfp-persistence/metadata.yaml
- charms/kfp-persistence/src/charm.py
- charms/kfp-persistence/src/components/pebble_components.py
- charms/kfp-schedwf/metadata.yaml
- charms/kfp-schedwf/src/charm.py
- charms/kfp-schedwf/src/components/pebble_component.py
- charms/kfp-viewer/metadata.yaml
- charms/kfp-viz/metadata.yaml
Closes canonical/pipelines-rocks#94
Closes canonical/pipelines-rocks#95
Closes canonical/pipelines-rocks#96
Closes canonical/pipelines-rocks#97
Closes canonical/pipelines-rocks#98
Closes canonical/pipelines-rocks#99
> chore: integrate 2.2.0 rocks

- charms/kfp-schedwf/src/charm.py
- charms/kfp-schedwf/src/components/pebble_component.py
- tests/integration/test_kfp_functional_v1.py
- tests/integration/test_kfp_functional_v2.py
Closes #517 
This PR updates the kfp-schedwf charm to use an empty namespace, similar to the one in [upstream](https://github.com/kubeflow/pipelines/blob/2.0.5/backend/Dockerfile.scheduledworkflow#L49).
Also, the `create_and_monitor_recurring_run` test is expanded to actually test that the run has been created and finished successfully.
> fix: watch for recurring runs in the correct namespace and expand integration tests for recurring runs

- charms/kfp-profile-controller/charmcraft.yaml
Remove the prime key from the charm part and instead move it to its dedicated scripts part to generate a valid charm.
The prime key has been deprecated and charmcraft 3.x and will no longer build valid charms that can be deployed.
For details about the fix, please refer to the issue.
Fixes #544
> fix: remove deprecated prime part from charmcraft.yaml file

- requirements-integration.txt
This change prevents juju from disconnecting and keeps compatibility with the latest `juju` agent used in the CI.
> ci: bump python-libjuju 3.2.x -> 3.5.x

- charms/kfp-ui/lib/charms/kubeflow_dashboard/v0/kubeflow_dashboard_links.py
part of fixing https://github.com/canonical/kubeflow-dashboard-operator/issues/213
bumps the `KubeflowDashboardLinks` lib to Patch 3, lib was updated in https://github.com/canonical/kubeflow-dashboard-operator/pull/219
> chore: bump dashboard links lib

- .github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
> ci(upload-charm): use charmcraft from latest/candidate in track/2.0

- .github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
> ci(upload-charm): use charmcraft from latest/candidate in track/2.2

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
This PR is part of closing [this issue](https://github.com/canonical/bundle-kubeflow/issues/1049).
It pins the channel used in our CI from `latest/candidate` to `latest/stable`.
Ideally we can unpin the version when [this issue](https://github.com/canonical/charmcraft/issues/1845) is fixed.
> Pin charmcraft channel to `3.1/stable`

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
This PR is a backport of #565. 
It is part of closing [this issue](https://github.com/canonical/bundle-kubeflow/issues/1049).
It pins the channel used in our CI from `latest/candidate` to `3.x/stable`.
Ideally we can unpin the version when [this issue](https://github.com/canonical/charmcraft/issues/1845) is fixed.
> chore(backport-2.0): Pin charmcraft channel to `3.x/stable`

- tools/get-images.sh
Closes #562
This PR updates `tools/get-images.sh` to be version agnostic when it comes to the `yq` utility. There is additional context in the [issue's description](https://github.com/canonical/kfp-operators/issues/562#issue-2492407938).
From experimentation, the Python version of `yq` also adds quotes to the output, so `tr` is called to remove any quote characters from all the entries.
To test:
- Run `bash tools/get-images.sh` with the snap version of `yq` (installed via `sudo snap install yq`)
- Run `bash tools/get-images.sh` with the Python verison of `yq` (installed via `pip install yq`)
- The output should be the same, and the same as when running `bash tools/get-images.sh` in the `main` branch.
> Update tools/get-images.sh to handle both Go and Python versions of yq

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
This PR is a backport of #565. 
It is part of closing [this issue](https://github.com/canonical/bundle-kubeflow/issues/1049).
It pins the channel used in our CI from `latest/candidate` to `3.x/stable`.
Ideally we can unpin the version when [this issue](https://github.com/canonical/charmcraft/issues/1845) is fixed.
> chore(backport-2.2): Pin charmcraft channel to `3.x/stable`

- charms/kfp-profile-controller/tests/integration/test_charm.py
> fix: Use channel to deploy minio

- charms/kfp-api/config.yaml
- charms/kfp-api/metadata.yaml
- charms/kfp-api/src/templates/auth_manifests.yaml.j2
- charms/kfp-metadata-writer/metadata.yaml
- charms/kfp-persistence/metadata.yaml
- charms/kfp-schedwf/metadata.yaml
- charms/kfp-ui/metadata.yaml
- charms/kfp-ui/src/charm.py
- charms/kfp-ui/src/components/pebble_components.py
- charms/kfp-viewer/metadata.yaml
- charms/kfp-viz/metadata.yaml
Upgrade manifests to 2.3.0. For producing the manifests, instructions in the [CONTRIBUTING.md](https://github.com/canonical/kfp-operators/blob/main/CONTRIBUTING.md) file were followed.
This includes:
* Upgrading images
* Updating kfp-api auth-manifests
* Introducing a new envvar in kfp-ui
Fixes #580
CI is fails mostly intermittently due to #602 and #601. Locally, they are successful (I hit #601 only once which looks unrelated to charms changes). I 've also refreshed a CKF deployment with the PR's charms and ran some pipelines, the kfp UAT and also enabled a recurring one.
> chore: Upgrade manifests to 2.3.0

- CONTRIBUTING.md
Follow up PR to #583.
Ref #580
> chore: update contributing.md file for manifests upgrade

- requirements-integration-v1.in
- requirements-integration-v1.txt
- tests/integration/test_kfp_functional_v1.py
- tests/integration/test_kfp_functional_v2.py
This is a workaround for #601. Changes should be reverted for uniformity among our charms once upstream https://github.com/juju/python-libjuju/issues/1204 is fixed.
Closes #601 
The CI has been rerun 4 times successfully (from the first commit).
> fix(ci): Use `juju wait-for` instead wait_for_idle()

- .github/workflows/integrate.yaml
- tests/integration/bundles/kfp_1.8_stable_install.yaml.j2
- tests/integration/bundles/kfp_latest_edge.yaml.j2
This PR introduces the following changes to help alleviate the Github runners disk pressure.
* ci, fix: change profile of mysql-k8s to testing
The mysql-k8s charm, used as kfp-db, has a profile configuration option that can
be set to testing which sets the scope of deployment. This option configures the
sizes of buffers it uses to a small number (and it allocates those buffers upon startup);
otherwise, it uses the pod's resources as it should in production. If the pod has resource
limits, the buffers will be allocated relative to these resource limits; otherwise it will
allocate relative to host machine's resources.
This is recommended for testing environments.
* ci: skip collection of debug artefacts on success
The Github runners for the KFP CI are getting out of storage by the
time the …
> ci, fix: change profile of mysql-k8s to testing, skip artefact collection on success

- charms/kfp-ui/config.yaml
- charms/kfp-ui/src/charm.py
- charms/kfp-ui/src/components/pebble_components.py
Part of #582 
Sets each of the following environment variables in `kfp-ui` to fix showing the logs after the workflow gets deleted:
* `ARGO_ARCHIVE_LOGS`
* `DISABLE_GKE_METADATA`
* `ARGO_KEYFORMAT`
Removes `ARGO_ARCHIVE_PREFIX` env var, as indicated by upstream in https://github.com/kubeflow/pipelines/pull/11010.
For testing, see https://github.com/canonical/kfp-operators/issues/582#issuecomment-2500003055
> feat: add envs to ensure kfp-ui can show logs

- .github/workflows/on_pull_request.yaml
This workflow enables the usage of canonical/charmed-kubeflow-workflows/.github/workflows/get_charms_build_with_cache.yaml for this CI, meaning that the integration tests and publish jobs are now able to download charm artefacts and use them consistently throught the various operations of this CI.
Fixes #641
Review and merge after https://github.com/canonical/charmed-kubeflow-workflows/pull/88
> ci: use get_charms_build_with_cache.yaml workflow

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
- charms/kfp-api/LICENSE
- charms/kfp-api/charmcraft.yaml
- charms/kfp-metadata-writer/LICENSE
- charms/kfp-metadata-writer/charmcraft.yaml
- charms/kfp-persistence/LICENSE
- charms/kfp-persistence/charmcraft.yaml
- charms/kfp-profile-controller/LICENSE
- charms/kfp-profile-controller/charmcraft.yaml
- charms/kfp-schedwf/LICENSE
- charms/kfp-schedwf/charmcraft.yaml
- charms/kfp-ui/LICENSE
- charms/kfp-ui/charmcraft.yaml
- charms/kfp-viewer/LICENSE
- charms/kfp-viewer/charmcraft.yaml
- charms/kfp-viz/LICENSE
- charms/kfp-viz/charmcraft.yaml
Closes #646 
TODO before merging to main: pin the quality checks workflow back to `main` once https://github.com/canonical/charmed-kubeflow-workflows/pull/91 gets merged.
Note to reviewer: the bundle integration tests are failing due to charmcraft 3.x/edge not working correctly with parallel builds, this will be resolved once https://github.com/canonical/kfp-operators/pull/645 is merged, where charmcraftcache is being used so the issue is no longer present.
PR is pointing to the dev brach [KF-6684-refactor-ci-with-build](https://github.com/canonical/kfp-operators/tree/KF-6684-refactor-ci-with-build), so it is expected to be merged in red and the CI will be addressed in:
#651 
#654 
#650
> Refactor charmcraft.yaml files to use `python` plugin and `st124` notation

- .github/workflows/integrate.yaml
- .github/workflows/on_pull_request.yaml
- .github/workflows/publish.yaml
This commit removes the extra abstraction of the get-charm-paths action and build_charm.yaml reusable workflow to avoid potential incompatibilities and sync issues with the data platforms workflows.
Notes to reviewer:
* the bundle tests will be addressed in #654 
* the on push workflow is now broken due to the changes, and it will be addressed in #650 
* the release and publish workflow will be addressed in #656
> ci: remove wrapper around get charm paths and build with cache workflows

- charms/kfp-api/charmcraft.yaml
- charms/kfp-metadata-writer/charmcraft.yaml
- charms/kfp-persistence/charmcraft.yaml
- charms/kfp-profile-controller/charmcraft.yaml
- charms/kfp-schedwf/charmcraft.yaml
- charms/kfp-ui/charmcraft.yaml
- charms/kfp-viewer/charmcraft.yaml
- charms/kfp-viz/charmcraft.yaml
Fixes issue where files in charm directory conflict with files created by python plugin during staging
> Use stage instead of prime in charmcraft files part

- tests/integration/test_kfp_functional_v1.py
- tests/integration/test_kfp_functional_v2.py
`wait-for` units instead of applications due to https://github.com/juju/juju/issues/18625.
> fix: wait-for units instead of applications

- .github/workflows/ci.yaml
- tests/README.md
- tests/integration/bundles/kfp_1.7_stable_install.yaml.j2
- tests/integration/bundles/kfp_1.8_stable_install.yaml.j2
- tests/integration/bundles/kfp_latest_edge.yaml.j2
- tests/integration/conftest.py
- tests/integration/helpers/bundle_mgmt.py
- tests/integration/helpers/localize_bundle.py
- tests/integration/test_kfp_functional_v1.py
- tests/integration/test_kfp_functional_v2.py
Closes #654 
This PR deprecates the `--no-build` option, that was used to deploy the charms from Charmhub and test them locally due to it not being used by the team.
* adds step to download charms built with cache before running bundle integration tests
* adds `--charms-path` parameter to pass to integration tests
* refactors the bundle integration test files to use the downloaded charms
Note to reviewer:
the single charm integration tests are failing due to https://github.com/canonical/kubeflow-ci/issues/152, this should be fixed by #663
> ci: use cache built charms in bundle tests

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
Removes the charmcraft channel pin now that charmcraft 3.3 is [released to stable](https://snapcraft.io/charmcraft)
> remove charmcraft pin to latest/candidate

- tests/integration/test_kfp_functional_v1.py
- tests/integration/test_kfp_functional_v2.py
wait-for units instead of applications due to juju/juju#18625.
> backport(fix): wait-for units instead of applications from #659

- charms/kfp-metadata-writer/metadata.yaml
Update image to use the one published by canonical/pipelines-rocks#168 which updates the name of the service created.
Fix canonical/pipelines-rocks#166
> fix: Update rock to one with proper service name

- charms/kfp-api/config.yaml
- charms/kfp-api/metadata.yaml
- charms/kfp-metadata-writer/metadata.yaml
- charms/kfp-persistence/metadata.yaml
- charms/kfp-profile-controller/files/upstream/sync.py
- charms/kfp-profile-controller/metadata.yaml
- charms/kfp-profile-controller/src/charm.py
- charms/kfp-profile-controller/src/default-custom-images.json
- charms/kfp-profile-controller/tests/unit/test_operator.py
- charms/kfp-schedwf/metadata.yaml
- charms/kfp-ui/metadata.yaml
- charms/kfp-ui/src/components/pebble_components.py
- charms/kfp-ui/src/templates/auth_manifests.yaml.j2
- charms/kfp-viewer/metadata.yaml
- charms/kfp-viz/metadata.yaml
Upgrade manifests and images to 2.4 according to instructions in the CONTRIBUTING.md file. For `securityContext` changes in upstream manifests, see #675.
Ref KF-6853
> chore: upgrade to 2.4.1

- charms/kfp-api/config.yaml
- charms/kfp-api/metadata.yaml
- charms/kfp-api/src/charm.py
- charms/kfp-metadata-writer/metadata.yaml
- charms/kfp-metadata-writer/src/components/pebble_component.py
- charms/kfp-persistence/metadata.yaml
- charms/kfp-persistence/src/components/pebble_components.py
- charms/kfp-profile-controller/config.yaml
- charms/kfp-profile-controller/metadata.yaml
- charms/kfp-profile-controller/src/default-custom-images.json
- charms/kfp-profile-controller/tests/unit/test_operator.py
- charms/kfp-schedwf/metadata.yaml
- charms/kfp-schedwf/src/components/pebble_component.py
- charms/kfp-ui/metadata.yaml
- charms/kfp-ui/src/components/pebble_components.py
- charms/kfp-viewer/metadata.yaml
- charms/kfp-viewer/src/components/pebble_component.py
- charms/kfp-viz/metadata.yaml
- charms/kfp-viz/src/components/pebble_components.py
* Integrate 2.4.1 rocks
* Update the container's `user` field in the each pebble plan according to canonical/kfp-operators#675
* Update contributing.md file
Close https://warthogs.atlassian.net/browse/KF-6938 (and all relevant integrate tasks)
The rocks integrated are from those jobs:
* viewer crd https://github.com/canonical/pipelines-rocks/actions/runs/13651064805/job/38160407837
* driver https://github.com/canonical/pipelines-rocks/actions/runs/13651225515/job/38160725716
* metadata-writer https://github.com/canonical/pipelines-rocks/actions/runs/13651117698/job/38160575489
* persistenceagent https://github.com/canonical/pipelines-rocks/actions/runs/13651108638/job/38160292729
* frontend https://github.com/canonical/pipelines-rocks/actions/runs/13651097370/job/38160646807#step:7:14
* …
> chore: integrate 2.4.1 rocks

- charms/kfp-api/terraform/variables.tf
- charms/kfp-metadata-writer/terraform/variables.tf
- charms/kfp-persistence/terraform/variables.tf
- charms/kfp-profile-controller/terraform/variables.tf
- charms/kfp-schedwf/terraform/variables.tf
- charms/kfp-ui/terraform/variables.tf
- charms/kfp-viewer/terraform/variables.tf
- charms/kfp-viz/terraform/variables.tf
fixes #685 
I realized this was actually missing only in track 2.3, and not in 2.2, e.g. see [here](https://github.com/canonical/kfp-operators/blob/track/2.2/charms/kfp-api/terraform/variables.tf#L10)
> [KF-7159] bug: terraform module  variable is not set in 2.3 track

- charms/kfp-profile-controller/tests/integration/test_charm.py
Deploy istio-pilot in kfp-profile-controller tests. This is required
after the change in canonical/kubeflow-profiles-operator#225.
Close #707
> fix(tests): Deploy istio-pilot in kfp-profile-controller tests

- .github/workflows/ci.yaml
This PR removes the {matrix-sdk} matrix completely in the `ci.yaml` file
> chore(ci): Remove SDK matrix in CI

- charms/kfp-api/requirements-unit.txt
- charms/kfp-api/requirements.in
- charms/kfp-api/requirements.txt
- charms/kfp-api/src/charm.py
Closes #698.
Note that we're also pinning the version of `cosl>=0.0.48` due to https://github.com/canonical/bundle-kubeflow/issues/1260
> feat: Add Grafana dashboard for `kfp-api`

- charms/kfp-metadata-writer/requirements-fmt.txt
- charms/kfp-metadata-writer/requirements-integration.txt
- charms/kfp-metadata-writer/requirements-lint.txt
- charms/kfp-metadata-writer/requirements-unit.txt
- charms/kfp-metadata-writer/requirements.in
- charms/kfp-metadata-writer/requirements.txt
- charms/kfp-ui/tests/integration/bundle.yaml.j2
This pull request addressed the note in the description of [this other pull request](https://github.com/canonical/kfp-operators/pull/723). See the latter for details.
Moreover, this pull request unpins a direct sub-charm dependency since its upgrades are no longer problematic with newer Ubuntu versions.
> chore: upgrade Ubuntu for newer test charm bases

- .github/workflows/ci.yaml
- concierge.yaml
Ref: https://github.com/canonical/bundle-kubeflow/issues/1334
This PR backports the update to use Canonical K8s in our integration tests. Note that we also backport a fix to use `24.04` as base in the `release-charm` action.
> (backport): Update CI to use Canonical K8s

- .github/workflows/ci.yaml
Ref: https://github.com/canonical/bundle-kubeflow/issues/1341
This PR backports a change to only run the `dump-charm-debug-artifacts` action on failure in order to save time.
> fix: Change dump-charm-debug-artifacts on failure
