.github/workflows/integrate.yaml
bundle.yaml
charms/kfp-persistence/metadata.yaml
charms/kfp-persistence/requirements.txt
charms/kfp-persistence/src/charm.py
charms/kfp-ui/metadata.yaml
charms/kfp-ui/src/charm.py

Also adds relation between `kfp-api` and `kfp-persistence`

Add ingress relation to kfp-ui

---

charms/kfp-api/src/sample_config.json

Remove broken sample pipelines

---

charms/kfp-api/metadata.yaml
charms/kfp-profile-controller/metadata.yaml
charms/kfp-ui/metadata.yaml
charms/kfp-viz/metadata.yaml

Remove deployment field from metadata.yaml in kfp-api, kfp-profile-controller, kfp-ui, and kfp-viz

Remove unneeded deployment from metadata.yaml

---

charms/kfp-api/metadata.yaml
charms/kfp-persistence/metadata.yaml
charms/kfp-profile-controller/metadata.yaml
charms/kfp-schedwf/metadata.yaml
charms/kfp-ui/metadata.yaml
charms/kfp-viewer/metadata.yaml

add min-juju-version to prevent PVCs being created

add min-juju-version to metadata

---

.gitignore
charms/kfp-ui/src/charm.py
charms/kfp-ui/tests/unit/test_operator.py

encode minio access and secret key in base64 and store in kubernetes secret

encode minio access and secret key

---

charms/kfp-viz/metadata.yaml

closes:https://github.com/canonical/bundle-kubeflow/issues/425

add min-juju-version

---

.gitignore
charms/kfp-profile-controller/src/charm.py
charms/kfp-profile-controller/tests/integration/test_charm.py
charms/kfp-ui/src/charm.py

Observe leader_settings_changed in kfp-ui and kfp-profile-controller

---

charms/kfp-viz/metadata.yaml

bump kfp-viz version to 2.0.0-alpha.3

---

charms/kfp-ui/metadata.yaml

bump kfp-ui version to 2.0.0-alpha.3

---

charms/kfp-viewer/metadata.yaml
charms/kfp-viewer/src/charm.py
charms/kfp-viewer/src/crds.yaml

Also adds a resource to a role that's used in v2.0.0-alpha.3

bump kf-viewer version to 2.0.0-alpha.3

---

charms/kfp-persistence/metadata.yaml

bump kfp-persistence version to 2.0.0-alpha.3

---

charms/kfp-api/metadata.yaml
charms/kfp-api/src/charm.py

Also modifies roles, liveliness probes to match upstream

bump kfp-api version to 2.0.0-alpha.3

---

charms/kfp-schedwf/metadata.yaml
charms/kfp-schedwf/src/charm.py
charms/kfp-schedwf/src/crds.yaml

Also:
* adds access to scheduledworkflow finalizers
* updates the scheduledworkflow CRD

bump kf-schedwf version to 2.0.0-alpha.3 

---

.github/workflows/integrate.yaml
charms/kfp-profile-controller/tests/integration/test_charm.py

Note: ~~This PR is against the kf-16-release branch~~ was against kf-16-release branch, but that was merged so now it goes directly against master

Update CI to use k8s 1.22

---

charms/kfp-profile-controller/README.md

This PR updates the README for the Kubeflow Pipelines Profile controller.

fix: update readme for kpf-profile-controller [skip ci]

---

charms/kfp-api/lib/charms/grafana_k8s/v0/grafana_dashboard.py
charms/kfp-api/lib/charms/observability_libs/v0/juju_topology.py
charms/kfp-api/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
charms/kfp-api/requirements.txt
charms/kfp-persistence/requirements.txt
charms/kfp-persistence/tests/unit/test_operator.py
charms/kfp-profile-controller/requirements.txt
charms/kfp-profile-controller/tests/unit/test_operator.py
charms/kfp-schedwf/requirements.txt
charms/kfp-ui/requirements.txt
charms/kfp-viewer/requirements.txt
charms/kfp-viz/requirements.txt

bump all charm libs to most recent versions

chore: bump all charm libs

---

.github/workflows/integrate.yaml
charms/kfp-api/metadata.yaml
charms/kfp-persistence/metadata.yaml
charms/kfp-persistence/src/charm.py
charms/kfp-schedwf/metadata.yaml
charms/kfp-ui/metadata.yaml
charms/kfp-viewer/metadata.yaml
charms/kfp-viz/metadata.yaml

git-xargs programmatic pull request

Update to 1.6.1

---

charms/kfp-api/lib/charms/grafana_k8s/v0/grafana_dashboard.py
charms/kfp-api/lib/charms/observability_libs/v0/juju_topology.py
charms/kfp-api/lib/charms/prometheus_k8s/v0/prometheus_scrape.py

- Library charms.prometheus_k8s.v0.prometheus_scrape updated to version 0.30.
- Library charms.observability_libs.v0.juju_topology updated to version 0.6.
- Library charms.grafana_k8s.v0.grafana_dashboard updated to version 0.24.

chore:bump all charm libs

---

.github/workflows/integrate.yaml
charms/kfp-api/src/charm.py
charms/kfp-api/tests/integration/test_charm.py
charms/kfp-api/tests/unit/test_operator.py

Merge dev branch into main to fix #163 and other problems that arose when trying to fix this other issue. These changes have already been reviewed in other PRs (see each commit for PR links).

Merge `dnplas-dev-fix-163` into `main`

---

charms/kfp-api/tests/README.md
charms/kfp-api/tests/integration/test_charm.py

In this PR:
* docs: update prometheus-scrape-config-k8s version
* tests: bump prometheus-scrape-config-k8s latest/beta latest/stable
Fixes #70

tests: bump prometheus-scrape-config-k8s latest/beta latest/stable

---

charms/kfp-api/metadata.yaml
charms/kfp-persistence/metadata.yaml
charms/kfp-profile-controller/src/charm.py
charms/kfp-schedwf/metadata.yaml
charms/kfp-ui/metadata.yaml
charms/kfp-viewer/metadata.yaml
charms/kfp-viz/metadata.yaml

Version bump to get latest released version.

feat: kfp version bump 2.0.0-alpha.6->2.0.0-alpha.7

---

charms/kfp-api/README.md

- Updated README to be inline with other charms. This REAME will be pulled into Charmhub.

docs: updated readme

---

charms/kfp-api/tox.ini

- Added update option to tox.ini to properly update dependencies.

fix: added update option to tox.ini

---

charms/kfp-api/requirements-fmt.txt
charms/kfp-api/requirements-integration.txt
charms/kfp-api/requirements-lint.txt
charms/kfp-api/requirements-unit.txt
charms/kfp-api/requirements.in
charms/kfp-api/requirements.txt
charms/kfp-api/src/charm.py
charms/kfp-api/tests/integration/test_charm.py
charms/kfp-api/tests/unit/test_operator.py
charms/kfp-api/tox.ini

- Modified test string in unit tests to refreclt updated SDI.
- Modified charm code to use handle errors.
- Updated requirements.

fix: fixed unit tests and charm code

---

charms/kfp-api/lib/charms/data_platform_libs/v0/data_interfaces.py
charms/kfp-api/metadata.yaml
charms/kfp-api/src/charm.py
charms/kfp-api/tests/integration/test_charm.py
charms/kfp-api/tests/unit/test_operator.py

https://github.com/canonical/kfp-operators/issues/201
- Added integration tests.
- Updated unit tests.
- Implemented msql and relational-db relation handling.

Kf 1696 gh201 feat mysql integration

---

charms/kfp-api/lib/charms/data_platform_libs/v0/data_interfaces.py
charms/kfp-api/lib/charms/grafana_k8s/v0/grafana_dashboard.py
charms/kfp-api/lib/charms/observability_libs/v1/kubernetes_service_patch.py
charms/kfp-api/lib/charms/prometheus_k8s/v0/prometheus_scrape.py

Bump kfp-api libs:
```
Library charms.data_platform_libs.v0.data_interfaces updated to version 0.16.                                                                                                    
Library charms.grafana_k8s.v0.grafana_dashboard updated to version 0.32.                                                                                                         
Library charms.observability_libs.v0.juju_topology was already up to date in version 0.6.                                                                                        
Library charms.observability_libs.v1.kubernetes_service_patch updated to version 1.7.                                                                                            
Library charms.prometheus_k8s.v0.prometheus_scrape updated to …
```

build: bump kfp-api libs

---

charms/kfp-profile-controller/charmcraft.yaml
charms/kfp-profile-controller/metadata.yaml
charms/kfp-profile-controller/requirements-unit.in
charms/kfp-profile-controller/requirements-unit.txt
charms/kfp-profile-controller/requirements.in
charms/kfp-profile-controller/requirements.txt
charms/kfp-profile-controller/src/charm.py
charms/kfp-profile-controller/src/components/pebble_components.py
charms/kfp-profile-controller/src/templates/crd_manifests.yaml.j2
charms/kfp-profile-controller/src/templates/secrets.yaml.j2
charms/kfp-profile-controller/tests/integration/test_charm.py
charms/kfp-profile-controller/tests/unit/test_operator.py
tests/integration/bundles/kfp_latest_edge.yaml.j2

- rewrite kfp-profile-controller with sidecar basecharm pattern
replaces #287.  See #287 for review discussion.

kfp-profile-controller Sidecar base charm implementation

---

charms/kfp-ui/metadata.yaml
charms/kfp-viz/metadata.yaml

Docs link (KF-4394 & KF-4396)

---

charms/kfp-api/CONTRIBUTING.md
charms/kfp-persistence/CONTRIBUTING.md
charms/kfp-profile-controller/CONTRIBUTING.md
charms/kfp-schedwf/CONTRIBUTING.md
charms/kfp-ui/CONTRIBUTING.md
charms/kfp-viewer/CONTRIBUTING.md
charms/kfp-viz/CONTRIBUTING.md

Added `CONTRIBUTING.md` files for all charms.

Contributing files

---

charms/kfp-schedwf/metadata.yaml

bump `kfp-schedwf` rock to v2 with the fix to issue https://github.com/canonical/pipelines-rocks/issues/38
partially addresses https://github.com/canonical/kfp-operators/issues/352

fix: bump kfp-schedwf rock version with patch

---

charms/kfp-api/metadata.yaml
charms/kfp-persistence/metadata.yaml
charms/kfp-schedwf/metadata.yaml
charms/kfp-ui/metadata.yaml
charms/kfp-ui/src/components/pebble_components.py
charms/kfp-viewer/metadata.yaml
charms/kfp-viz/metadata.yaml

Integrate ROCKs into charms
I ran UATs and created some runs from the Shared pipelines examples and they were all successful.
Closes #388

feat: Integrate ROCKs into charms

---

charms/kfp-api/metadata.yaml
charms/kfp-persistence/metadata.yaml
charms/kfp-schedwf/metadata.yaml
charms/kfp-ui/metadata.yaml
charms/kfp-ui/src/components/pebble_components.py
charms/kfp-viewer/metadata.yaml
charms/kfp-viz/metadata.yaml

* Integrate ROCKs into charms
* Modify `kfp-ui` command according to ROCK
Refs #388

cherry-pick(feat): Integrate ROCKs into charms from #398

---

charms/kfp-metadata-writer/metadata.yaml

Closes canonical/pipelines-rocks#66

feat: Integrate ROCK in metadata-writer

---

charms/kfp-metadata-writer/metadata.yaml

Closes canonical/pipelines-rocks#66

feat: Integrate ROCK in metadata-writer charm

---

CONTRIBUTING.md

Note that there are CONTRIBUTING.md files in each of the charms, but since changes usually take place at the same time for all of the charms, I added this file at the repo-level.

Add repo-level CONTRIBUTING.md file including information for Updating manifests

---

CONTRIBUTING.md
charms/kfp-api/config.yaml
charms/kfp-api/metadata.yaml
charms/kfp-api/src/charm.py
charms/kfp-api/src/templates/auth_manifests.yaml.j2
charms/kfp-api/tests/unit/test_operator.py
charms/kfp-metadata-writer/metadata.yaml
charms/kfp-persistence/config.yaml
charms/kfp-persistence/metadata.yaml
charms/kfp-persistence/src/charm.py
charms/kfp-persistence/src/templates/auth_manifests.yaml.j2
charms/kfp-persistence/tests/unit/test_operator.py
charms/kfp-schedwf/config.yaml
charms/kfp-schedwf/metadata.yaml
charms/kfp-schedwf/src/charm.py
charms/kfp-schedwf/src/components/pebble_component.py
charms/kfp-schedwf/tests/unit/test_operator.py
charms/kfp-ui/metadata.yaml
charms/kfp-viewer/metadata.yaml
charms/kfp-viz/metadata.yaml

* Update manifests for all kfp charms 
* Add repo-level CONTRIBUTING.md file with instructions for updating manifests

chore: bump manifests 2.0.3 -> 2.2.0

---

charms/kfp-api/requirements-integration.txt
charms/kfp-api/requirements-unit.txt
charms/kfp-metadata-writer/requirements-integration.txt
charms/kfp-persistence/requirements-integration.txt
charms/kfp-profile-controller/requirements-integration.txt
charms/kfp-profile-controller/requirements-unit.txt
charms/kfp-schedwf/requirements-integration.txt
charms/kfp-ui/requirements-integration.txt
charms/kfp-viewer/requirements-integration.txt
charms/kfp-viz/requirements-integration.txt

Part of canonical/bundle-kubeflow#868

build: bump ops to latest possible version

---

charms/kfp-api/requirements-integration.txt
charms/kfp-metadata-writer/requirements-integration.txt
charms/kfp-persistence/requirements-integration.txt
charms/kfp-profile-controller/requirements-integration.txt
charms/kfp-schedwf/requirements-integration.txt
charms/kfp-ui/requirements-integration.txt
charms/kfp-viewer/requirements-integration.txt
charms/kfp-viz/requirements-integration.txt

Build charmed-kubeflow-chisme for requirements-integration.txt.
Part of canonical/charmed-kubeflow-chisme#104

build, tests: bump charmed-kubeflow-chisme 0.4.0 -> 0.4.1

---

charms/kfp-profile-controller/tests/integration/test_charm.py

backport(fix): Use channel to deploy minio from #598

---

.github/workflows/integrate.yaml
requirements-integration-v1.in
requirements-integration-v1.txt
tests/README.md
tests/integration/conftest.py
tests/integration/helpers/charmcraft.py
tests/integration/test_kfp_functional_v1.py
tests/integration/test_kfp_functional_v2.py

fix(ci): Run `charmcraft clean` on bundle integration tests

---

.github/workflows/integrate.yaml
CONTRIBUTING.md
charms/kfp-api/config.yaml
charms/kfp-api/metadata.yaml
charms/kfp-api/src/templates/auth_manifests.yaml.j2
charms/kfp-metadata-writer/metadata.yaml
charms/kfp-persistence/metadata.yaml
charms/kfp-schedwf/metadata.yaml
charms/kfp-ui/metadata.yaml
charms/kfp-ui/src/charm.py
charms/kfp-ui/src/components/pebble_components.py
charms/kfp-viewer/metadata.yaml
charms/kfp-viz/metadata.yaml
requirements-integration-v1.in
requirements-integration-v1.txt
tests/README.md
tests/integration/conftest.py
tests/integration/helpers/charmcraft.py
tests/integration/test_kfp_functional_v1.py
tests/integration/test_kfp_functional_v2.py

This PR merges the `dev-upgrade-kfp-2.3.0` dev branch to `main`:
* #583 
* #610
* #616

Merge upgrade kfp to 2.3.0 dev branch to `main`

---

charms/kfp-api/metadata.yaml

chore: integrate api-server:2.3.0-5e9542c into kfp-api

---

charms/kfp-viz/metadata.yaml

chore: integrate visualization-server:2.3.0-a2f7f9e into kfp-viz

---

charms/kfp-metadata-writer/metadata.yaml

chore: integrate metadata-writer:2.3.0-519bac2 into kfp-metadata-writer

---

charms/kfp-schedwf/metadata.yaml

chore: integrate scheduledworkflow:2.3.0-74164db into kfp-schedwf

---

charms/kfp-persistence/metadata.yaml

chore: integrate persistenceagent:2.3.0-0c6ce7c into kfp-persistence

---

charms/kfp-viewer/metadata.yaml

chore: integrate viewer-crd-controller:2.3.0-60337e3 into kfp-view

---

charms/kfp-ui/metadata.yaml

chore: integrate frontend:2.3.0-111c139 into kfp-ui

---

.github/workflows/ci.yaml

Ref canonical/bundle-kubeflow#1157

chore(ci): bump microk8s to 1.31

---

charms/kfp-api/charmcraft.yaml
charms/kfp-persistence/charmcraft.yaml
charms/kfp-profile-controller/charmcraft.yaml
charms/kfp-schedwf/charmcraft.yaml
charms/kfp-ui/charmcraft.yaml
charms/kfp-viewer/charmcraft.yaml
charms/kfp-viz/charmcraft.yaml

For the CI, see https://github.com/canonical/bundle-kubeflow/issues/1178#issuecomment-2519888041
Ref canonical/bundle-kubeflow#1178

build: Enable building rust dependencies

---

charms/kfp-api/lib/charms/data_platform_libs/v0/data_interfaces.py
charms/kfp-api/lib/charms/grafana_k8s/v0/grafana_dashboard.py
charms/kfp-api/lib/charms/loki_k8s/v1/loki_push_api.py
charms/kfp-api/lib/charms/observability_libs/v1/kubernetes_service_patch.py
charms/kfp-api/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
charms/kfp-metadata-writer/lib/charms/loki_k8s/v1/loki_push_api.py
charms/kfp-persistence/lib/charms/loki_k8s/v1/loki_push_api.py
charms/kfp-profile-controller/lib/charms/loki_k8s/v1/loki_push_api.py
charms/kfp-profile-controller/lib/charms/observability_libs/v1/kubernetes_service_patch.py
charms/kfp-schedwf/lib/charms/loki_k8s/v1/loki_push_api.py
charms/kfp-ui/lib/charms/loki_k8s/v1/loki_push_api.py
charms/kfp-ui/lib/charms/observability_libs/v1/kubernetes_service_patch.py
charms/kfp-viewer/lib/charms/loki_k8s/v1/loki_push_api.py
charms/kfp-viz/lib/charms/loki_k8s/v1/loki_push_api.py
charms/kfp-viz/lib/charms/observability_libs/v1/kubernetes_service_patch.py

* Bump libraries using charmcraft fetch-lib.
* Check for major versions using noctua charm libraries check --major. If there is one, then commit a do-not-merge-message.txt file.
Ref canonical/bundle-kubeflow#1184

chore: bump libraries

---

.github/workflows/ci.yaml

backport(fix): update logs action from #663

---

charms/kfp-ui/src/components/pebble_components.py

chore: fix rocks terminology

---

.github/workflows/ci.yaml
.github/workflows/promote.yaml

chore(ci): bump GH runners to ubuntu-24.04

---

charms/kfp-api/terraform/versions.tf
charms/kfp-metadata-writer/terraform/versions.tf
charms/kfp-persistence/terraform/versions.tf
charms/kfp-profile-controller/terraform/versions.tf
charms/kfp-schedwf/terraform/versions.tf
charms/kfp-ui/terraform/versions.tf
charms/kfp-viewer/terraform/versions.tf
charms/kfp-viz/terraform/versions.tf

Updating juju provider requirement to >=0.14.0

[KF-7255] Update Juju provider

---

charms/kfp-api/terraform/variables.tf
charms/kfp-api/terraform/versions.tf
charms/kfp-metadata-writer/terraform/variables.tf
charms/kfp-metadata-writer/terraform/versions.tf
charms/kfp-persistence/terraform/variables.tf
charms/kfp-persistence/terraform/versions.tf
charms/kfp-profile-controller/terraform/variables.tf
charms/kfp-profile-controller/terraform/versions.tf
charms/kfp-schedwf/terraform/variables.tf
charms/kfp-schedwf/terraform/versions.tf
charms/kfp-ui/terraform/variables.tf
charms/kfp-ui/terraform/versions.tf
charms/kfp-viewer/terraform/variables.tf
charms/kfp-viewer/terraform/versions.tf
charms/kfp-viz/terraform/variables.tf
charms/kfp-viz/terraform/versions.tf

Cutting new release for branch track/2.4

[KF-7254] Release 1.10

---

charms/kfp-api/terraform/variables.tf
charms/kfp-metadata-writer/terraform/variables.tf
charms/kfp-persistence/terraform/variables.tf
charms/kfp-profile-controller/terraform/variables.tf
charms/kfp-schedwf/terraform/variables.tf
charms/kfp-ui/terraform/variables.tf
charms/kfp-viewer/terraform/variables.tf
charms/kfp-viz/terraform/variables.tf

[KF-7268] chore: pin channel to latest/edge

---

.github/workflows/tiobe_scan.yml
charms/kfp-api/tox.ini
charms/kfp-metadata-writer/tox.ini
charms/kfp-persistence/tox.ini
charms/kfp-profile-controller/tox.ini
charms/kfp-schedwf/tox.ini
charms/kfp-ui/tox.ini
charms/kfp-viewer/tox.ini
charms/kfp-viz/tox.ini

Updating with TIOBE scan, including:
* reformatting tox.ini file to be machine-generated and handled
* coverage.xml generation when running unit tests 
* creating tiobe_scan.yaml file

[KF-7281] Enabling TIOBE scan

---

charms/kfp-api/terraform/variables.tf
charms/kfp-metadata-writer/terraform/variables.tf
charms/kfp-persistence/terraform/variables.tf
charms/kfp-profile-controller/terraform/variables.tf
charms/kfp-schedwf/terraform/variables.tf
charms/kfp-ui/terraform/variables.tf
charms/kfp-viewer/terraform/variables.tf
charms/kfp-viz/terraform/variables.tf

chore: update terraform modules channel to 2.5/stable
